// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/resources/newFile.proto

package org.google.protobuf.demo;

public final class PersonDemo {
  private PersonDemo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string name = 1;</code>
     */
    com.google.protobuf.ProtocolStringList
        getNameList();
    /**
     * <code>repeated string name = 1;</code>
     */
    int getNameCount();
    /**
     * <code>repeated string name = 1;</code>
     */
    java.lang.String getName(int index);
    /**
     * <code>repeated string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes(int index);

    /**
     * <code>repeated int32 id_Card = 2;</code>
     */
    java.util.List<java.lang.Integer> getIdCardList();
    /**
     * <code>repeated int32 id_Card = 2;</code>
     */
    int getIdCardCount();
    /**
     * <code>repeated int32 id_Card = 2;</code>
     */
    int getIdCard(int index);

    /**
     * <code>repeated string id = 3;</code>
     */
    com.google.protobuf.ProtocolStringList
        getIdList();
    /**
     * <code>repeated string id = 3;</code>
     */
    int getIdCount();
    /**
     * <code>repeated string id = 3;</code>
     */
    java.lang.String getId(int index);
    /**
     * <code>repeated string id = 3;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes(int index);
  }
  /**
   * Protobuf type {@code Person}
   */
  public  static final class Person extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Person)
      PersonOrBuilder {
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Person() {
      name_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      idCard_ = java.util.Collections.emptyList();
      id_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                name_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              name_.add(bs);
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                idCard_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              idCard_.add(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                idCard_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                idCard_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                id_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              id_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          name_ = name_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          idCard_ = java.util.Collections.unmodifiableList(idCard_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          id_ = id_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.google.protobuf.demo.PersonDemo.internal_static_Person_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.google.protobuf.demo.PersonDemo.internal_static_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.google.protobuf.demo.PersonDemo.Person.class, org.google.protobuf.demo.PersonDemo.Person.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList name_;
    /**
     * <code>repeated string name = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getNameList() {
      return name_;
    }
    /**
     * <code>repeated string name = 1;</code>
     */
    public int getNameCount() {
      return name_.size();
    }
    /**
     * <code>repeated string name = 1;</code>
     */
    public java.lang.String getName(int index) {
      return name_.get(index);
    }
    /**
     * <code>repeated string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes(int index) {
      return name_.getByteString(index);
    }

    public static final int ID_CARD_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> idCard_;
    /**
     * <code>repeated int32 id_Card = 2;</code>
     */
    public java.util.List<java.lang.Integer>
        getIdCardList() {
      return idCard_;
    }
    /**
     * <code>repeated int32 id_Card = 2;</code>
     */
    public int getIdCardCount() {
      return idCard_.size();
    }
    /**
     * <code>repeated int32 id_Card = 2;</code>
     */
    public int getIdCard(int index) {
      return idCard_.get(index);
    }

    public static final int ID_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList id_;
    /**
     * <code>repeated string id = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getIdList() {
      return id_;
    }
    /**
     * <code>repeated string id = 3;</code>
     */
    public int getIdCount() {
      return id_.size();
    }
    /**
     * <code>repeated string id = 3;</code>
     */
    public java.lang.String getId(int index) {
      return id_.get(index);
    }
    /**
     * <code>repeated string id = 3;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes(int index) {
      return id_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < name_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, name_.getRaw(i));
      }
      for (int i = 0; i < idCard_.size(); i++) {
        output.writeInt32(2, idCard_.get(i));
      }
      for (int i = 0; i < id_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, id_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < name_.size(); i++) {
          dataSize += computeStringSizeNoTag(name_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getNameList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < idCard_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(idCard_.get(i));
        }
        size += dataSize;
        size += 1 * getIdCardList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < id_.size(); i++) {
          dataSize += computeStringSizeNoTag(id_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getIdList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static org.google.protobuf.demo.PersonDemo.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.google.protobuf.demo.PersonDemo.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.google.protobuf.demo.PersonDemo.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.google.protobuf.demo.PersonDemo.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.google.protobuf.demo.PersonDemo.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.google.protobuf.demo.PersonDemo.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.google.protobuf.demo.PersonDemo.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.google.protobuf.demo.PersonDemo.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.google.protobuf.demo.PersonDemo.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.google.protobuf.demo.PersonDemo.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.google.protobuf.demo.PersonDemo.Person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Person)
        org.google.protobuf.demo.PersonDemo.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.google.protobuf.demo.PersonDemo.internal_static_Person_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.google.protobuf.demo.PersonDemo.internal_static_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.google.protobuf.demo.PersonDemo.Person.class, org.google.protobuf.demo.PersonDemo.Person.Builder.class);
      }

      // Construct using org.google.protobuf.demo.PersonDemo.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        idCard_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.google.protobuf.demo.PersonDemo.internal_static_Person_descriptor;
      }

      public org.google.protobuf.demo.PersonDemo.Person getDefaultInstanceForType() {
        return org.google.protobuf.demo.PersonDemo.Person.getDefaultInstance();
      }

      public org.google.protobuf.demo.PersonDemo.Person build() {
        org.google.protobuf.demo.PersonDemo.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.google.protobuf.demo.PersonDemo.Person buildPartial() {
        org.google.protobuf.demo.PersonDemo.Person result = new org.google.protobuf.demo.PersonDemo.Person(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          name_ = name_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.name_ = name_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          idCard_ = java.util.Collections.unmodifiableList(idCard_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.idCard_ = idCard_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          id_ = id_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.id_ = id_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.google.protobuf.demo.PersonDemo.Person) {
          return mergeFrom((org.google.protobuf.demo.PersonDemo.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.google.protobuf.demo.PersonDemo.Person other) {
        if (other == org.google.protobuf.demo.PersonDemo.Person.getDefaultInstance()) return this;
        if (!other.name_.isEmpty()) {
          if (name_.isEmpty()) {
            name_ = other.name_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureNameIsMutable();
            name_.addAll(other.name_);
          }
          onChanged();
        }
        if (!other.idCard_.isEmpty()) {
          if (idCard_.isEmpty()) {
            idCard_ = other.idCard_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureIdCardIsMutable();
            idCard_.addAll(other.idCard_);
          }
          onChanged();
        }
        if (!other.id_.isEmpty()) {
          if (id_.isEmpty()) {
            id_ = other.id_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureIdIsMutable();
            id_.addAll(other.id_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.google.protobuf.demo.PersonDemo.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.google.protobuf.demo.PersonDemo.Person) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList name_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureNameIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          name_ = new com.google.protobuf.LazyStringArrayList(name_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string name = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getNameList() {
        return name_.getUnmodifiableView();
      }
      /**
       * <code>repeated string name = 1;</code>
       */
      public int getNameCount() {
        return name_.size();
      }
      /**
       * <code>repeated string name = 1;</code>
       */
      public java.lang.String getName(int index) {
        return name_.get(index);
      }
      /**
       * <code>repeated string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes(int index) {
        return name_.getByteString(index);
      }
      /**
       * <code>repeated string name = 1;</code>
       */
      public Builder setName(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureNameIsMutable();
        name_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string name = 1;</code>
       */
      public Builder addName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureNameIsMutable();
        name_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string name = 1;</code>
       */
      public Builder addAllName(
          java.lang.Iterable<java.lang.String> values) {
        ensureNameIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, name_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string name = 1;</code>
       */
      public Builder clearName() {
        name_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string name = 1;</code>
       */
      public Builder addNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureNameIsMutable();
        name_.add(value);
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> idCard_ = java.util.Collections.emptyList();
      private void ensureIdCardIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          idCard_ = new java.util.ArrayList<java.lang.Integer>(idCard_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int32 id_Card = 2;</code>
       */
      public java.util.List<java.lang.Integer>
          getIdCardList() {
        return java.util.Collections.unmodifiableList(idCard_);
      }
      /**
       * <code>repeated int32 id_Card = 2;</code>
       */
      public int getIdCardCount() {
        return idCard_.size();
      }
      /**
       * <code>repeated int32 id_Card = 2;</code>
       */
      public int getIdCard(int index) {
        return idCard_.get(index);
      }
      /**
       * <code>repeated int32 id_Card = 2;</code>
       */
      public Builder setIdCard(
          int index, int value) {
        ensureIdCardIsMutable();
        idCard_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 id_Card = 2;</code>
       */
      public Builder addIdCard(int value) {
        ensureIdCardIsMutable();
        idCard_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 id_Card = 2;</code>
       */
      public Builder addAllIdCard(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureIdCardIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, idCard_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 id_Card = 2;</code>
       */
      public Builder clearIdCard() {
        idCard_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList id_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureIdIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          id_ = new com.google.protobuf.LazyStringArrayList(id_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string id = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getIdList() {
        return id_.getUnmodifiableView();
      }
      /**
       * <code>repeated string id = 3;</code>
       */
      public int getIdCount() {
        return id_.size();
      }
      /**
       * <code>repeated string id = 3;</code>
       */
      public java.lang.String getId(int index) {
        return id_.get(index);
      }
      /**
       * <code>repeated string id = 3;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes(int index) {
        return id_.getByteString(index);
      }
      /**
       * <code>repeated string id = 3;</code>
       */
      public Builder setId(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIdIsMutable();
        id_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string id = 3;</code>
       */
      public Builder addId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIdIsMutable();
        id_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string id = 3;</code>
       */
      public Builder addAllId(
          java.lang.Iterable<java.lang.String> values) {
        ensureIdIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, id_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string id = 3;</code>
       */
      public Builder clearId() {
        id_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string id = 3;</code>
       */
      public Builder addIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIdIsMutable();
        id_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Person)
    }

    // @@protoc_insertion_point(class_scope:Person)
    private static final org.google.protobuf.demo.PersonDemo.Person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.google.protobuf.demo.PersonDemo.Person();
    }

    public static org.google.protobuf.demo.PersonDemo.Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Person>
        PARSER = new com.google.protobuf.AbstractParser<Person>() {
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Person(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<Person> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    public org.google.protobuf.demo.PersonDemo.Person getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Person_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Person_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034main/resources/newFile.proto\"3\n\006Person" +
      "\022\014\n\004name\030\001 \003(\t\022\017\n\007id_Card\030\002 \003(\005\022\n\n\002id\030\003 " +
      "\003(\tB&\n\030org.google.protobuf.demoB\nPersonD" +
      "emo"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Person_descriptor,
        new java.lang.String[] { "Name", "IdCard", "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
